source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => '8.0'

inhibit_all_warnings!
use_frameworks!

target 'NavigationDemo' do
   pod 'Marshroute', :path => '../'
end

target 'MarshrouteTests' do
   pod 'Marshroute', :path => '../'
end
