source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => '9.0'

inhibit_all_warnings!
use_frameworks!

target 'MarshrouteExample' do
   pod 'Marshroute', :path => '../'
   
   target 'MarshrouteTests' do
       inherit! :search_paths
   end
end
